### ISSUE TITLE
BGR2RGB in examples

### ISSUE THREAD

**Issue by DaniilOr** [silvermete0r/redeepfake-demo-app#1]
Hi, it seems like in the "Test on random set of 20 images" section of your README you did not change the colors order from BGR to RGB (that is basically why the images are blue). Please correct it :D

**Comment by silvermete0r** [comment]
face_recognition library in python uses BGR format. Training data consists of BGR formatted 224x224 images of faces. So, in examples also BGR format was used. But in  the demo app, images converted to RGB for better visual image. Try to use demo app in huggingface 👍

Thank you for the comment!
